# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  encoding: utf8
  adapter: postgresql
  database: pestulon_development
test:
  encoding: utf8
  adapter: postgresql
  database: pestulon_test
