# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: utf8
  adapter: postgresql
development:
  <<: *default
  database: pestulon_development
test:
  <<: *default
  database: pestulon_test
production:
  <<: *default
  database: pestulon_production